on: workflow_dispatch
      
jobs:
  test:
    runs-on: windows-latest
    timeout-minutes: 3

    steps:
      - name: Set the value in pwsh
        id: step_one
        run: |  
          -join (1..15 | ForEach {[char]((48..57)+(65..90)+(97..122) | Get-Random)}) | set EOF
          #"JSON_RESPONSE<<$EOF" >> $env:GITHUB_OUTPUT
          #(Invoke-WebRequest -Uri "https://raw.githubusercontent.com/ee090186/GitHubActionsTest/main/README.md").Content >> $env:GITHUB_OUTPUT
          #"$EOF" >> $env:GITHUB_OUTPUT
          
          $gitgraph_text = "abc" + "`r`n" + "def"
          Write-Output $gitgraph_text
          "text<<$EOF" >> $env:GITHUB_OUTPUT
          $gitgraph_text >> $env:GITHUB_OUTPUT
          "$EOF" >> $env:GITHUB_OUTPUT
        shell: pwsh

      - name: Use the value
        id: step_two
        run: |
          Write-Output "${{ steps.step_one.outputs.text }}"
